### ISSUE TITLE
Consider using a build tool like Vite or Astro

### ISSUE THREAD

**Issue by mucookul** [YTLitePlus/ytliteplus.github.io#2]
Currently, this app is very hard to update, if you want to add another page, there's a lot of copy and pasting, also it's very unoptimized (less important since it's so small). I can help in migrating to Vite or Astro.

**Comment by Balackburn** [comment]
Hello didn't saw your proposition, would be a great improvement, you can fork this repostory and make a PR if you want.

**Comment by mucookul** [comment]
Already have, making final touches

**Comment by Balackburn** [comment]
> Already have, making final touches

Great thank you for your contribution.

**Comment by mucookul** [comment]
by the way, is me using https://tailwindcss.com/ okay?

**Comment by Balackburn** [comment]
Yes no problem

**Comment by mucookul** [comment]
Published my copy here: https://ytliteplus-github-io.pages.dev/, https://github.com/Mukul1127/ytliteplus.github.io

**Comment by Balackburn** [comment]
> Published my copy here: https://ytliteplus-github-io.pages.dev/, https://github.com/Mukul1127/ytliteplus.github.io

Thank you for your work unfortunatly they are a few layout issues it's not a 1:1 update, could you update it to be more close to original so I can merge it? Thank you

**Comment by mucookul** [comment]
Yeah it's a recreation, made it closer

**Comment by mucookul** [comment]
I also added a simple custom alert for when download link isn't found in latest release

**Comment by mucookul** [comment]
Also forgot to ask, do you want to put it under a license like AGPL-3.0, here's a good resource: https://choosealicense.com/, https://choosealicense.com/licenses/agpl-3.0/

**Comment by Balackburn** [comment]
> Also forgot to ask, do you want to put it under a license like AGPL-3.0, here's a good resource: https://choosealicense.com/, https://choosealicense.com/licenses/agpl-3.0/

Yes thank you, could you make the "Screenshots" subtitle not scroll with the screenshots, and the same border radius for buttons as original. Otherwise great works, thank you!

**Comment by mucookul** [comment]
Ohhh, overlooked that, will fix

**Comment by mucookul** [comment]
Updated

**Comment by mucookul** [comment]
> > Also forgot to ask, do you want to put it under a license like AGPL-3.0, here's a good resource: [choosealicense.com](https://choosealicense.com/), [choosealicense.com/licenses/agpl-3.0](https://choosealicense.com/licenses/agpl-3.0/)
> 
> Yes thank you, could you make the "Screenshots" subtitle not scroll with the screenshots, and the same border radius for buttons as original. Otherwise great works, thank you!

Also do you mean that you want AGPL-3.0?

**Comment by Balackburn** [comment]
Yes and if you could use the same max-width and space between YTLitePlus, subtext, buttons and the Logo (same as original), It would be an almost perfect copy

**Comment by mucookul** [comment]
Done. Also added another footer saying the website is licensed at the bottom

**Comment by Balackburn** [comment]
Sorry but it's still not a 1:1 copy, also their is a problem with the button :
![Screenshot 2024-09-30 at 23-25-34 YTLitePlus - Supercharge Your YouTube Experience](https://github.com/user-attachments/assets/f6a08962-7c77-48ae-84f5-d1cfc5ba1c05) 

The buttons should be aligned with YTLitePlus logo, and the subtext should not be the same typo (lighter) as YTLitePlus title,

Also having 2 footers is kind of weird looking, 

Also the download icon added to the download ipa button doesn't look native you can use SF pro symbols from Apple or remove it (and it's not at the same position as original)
(something like this : 
![Screenshot 2024-09-30 at 23-25-34 YTLitePlus - Supercharge Your YouTube Experience](https://github.com/user-attachments/assets/5e5c3481-6880-4b92-9f2a-d528ef632ef9) )


Otherwise thank you, will merge after it's finished.

**Comment by Mukul1127** [comment]
Ok

**Comment by Mukul1127** [comment]
Also which button do you mean, the theme changer button?

**Comment by mucookul** [comment]
The buttons are like that as there isn't enough room to put them on 1 line so it wrapped instead of stretching

**Comment by mucookul** [comment]
Also about the download button, it seems like doing that would completely violate Apple's license. Also even if I could, it seems to be impossible to get the icon as it only comes in a dmg. I'm on windows.

**Comment by mucookul** [comment]
Fixed the 2nd and 3rd issue.

**Comment by mucookul** [comment]
![{66768790-5A4F-40D7-9C6C-6AC0BF641973}](https://github.com/user-attachments/assets/da31fd4e-b647-4694-9a1f-2b2c363aaab9)

**Comment by Balackburn** [comment]
I was speaking about the 3 buttons, they should be alignated with the YTLitePlus logo :




![SCR-20241001-kcdv](https://github.com/user-attachments/assets/30183647-5ae8-4504-aef5-3418716c19f8)

**Comment by mucookul** [comment]
Okay, I have fixed those issues and I also swapped the download icon for one that is closer to the sf pro symbols from heroicons

**Comment by Balackburn** [comment]
Done, thank you
